export const SET_DRINKS = "SET_DRINKS";
export const SET_SEARCHED_DRINK = "SET_SEARCHED_DRINK";
export const SET_RANDOM_DRINK = "SET_RANDOM_DRINK";
export const SET_CURRENT_DRINK = "SET_CURRENT_DRINK";
export const SET_SORTING_ORDER = "SET_SORTING_ORDER";

